name: Deploy Project Neapolitan

on:
  workflow_run:
    workflows: ["Run Tests on Project Neapolitan"]
    types:
      - completed
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./client

      - name: Build the frontend
        run: npm run build
        working-directory: ./client
        env:
          CI: false
          REACT_APP_BACKEND_URL: ${{ secrets.BACKEND_URL }}
          REACT_APP_ENV: production
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync ./client/build/ s3://neapolitandebt.com --delete

  deploy-backend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker
        run: |
          cd ./server
          docker build \
          --build-arg FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
          --build-arg AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }} \
          --build-arg AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }} \
          -t neapolitan-backend .
          docker tag neapolitan-backend:latest ${{ steps.login-ecr.outputs.registry }}/neapolitan-backend:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/neapolitan-backend:latest

      - name: Force ECS Service Update
        run: |
          aws ecs update-service \
            --cluster neapolitan-cluster \
            --service arn:aws:ecs:us-east-1:390844751276:service/neapolitan-cluster/neapolitan-backend-task-service-j4ed08lj \
            --force-new-deployment \
            --region us-east-1
